server.port=${PORT:8081}

spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=chatapp

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.security.user.password=disabled

logging.level.com.chatapp=DEBUG